name: sci
channels:
  - pyviz 
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - gdal
  - qgis
  - azure-storage-blob
  - basemap
  - biopython
  - bitarray
  - bokeh
  - cython
  - descartes
  - earthengine-api
  - eofs
  - fiona
  - folium
  - fsspec
  - fuzzywuzzy
  - gcsfs
  - geemap
  - geographiclib
  - geojson
  - geopandas
  - geopy
  - geos
  - imageio
  - intake
  - intake-stac
  - intake-xarray
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - jupyter_client
  - keras
  - latlon_utils
  - mahotas
  - mapclassify
  - matplotlib
  - matplotlib-inline
  - msprime
  - netCDF4
  - numpy
  - oauth2client
  - palettable
  - pandas
  - planetary_computer
  - psutil
  - pykrige
  - pyproj
  - pysal
  - python-dateutil
  - python-Levenshtein
  - pyVCF
  - radian
  - rasterio
  - rasterstats
  - rio-cogeo
  - rio-color
  - rio-tiler
  - rio-viz
  - rioxarray
  - s3fs
  - scikit-bio
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - sphinx
  - sphinx_rtd_theme
  - stackstac
  - statsmodels
  - sympy
  - tensorflow
  - tskit
  - twine
  - unidecode
  - urllib3
  - wget
  - xarray
  - xarray-spatial
  - zarr
  - r-base>=4.0
  - r-caTools
  - r-CCP
  - r-cowplot
  - r-devtools
  - r-dismo
  - r-dplyr
  - r-forecast
  - r-ggplot2
  - r-ggthemes
  - r-gstat
  - r-hierfstat
  - r-irkernel
  - r-jsonlite
  - r-knitr
  - r-latex2exp
  - r-lme4
  - r-lmerTest
  - r-mapedit
  - r-mapview
  - r-MASS
  - r-nlme
  - r-pals
  - r-phytools
  - r-plyr
  - r-PopGenReport
  - r-randomForest
  - r-raster
  - r-rasterVis
  - r-rayshader
  - r-RColorBrewer
  - r-readr
  - r-reshape2
  - r-rgdal
  - r-rmarkdown
  - r-SDMTools
  - r-sf
  - r-shiny
  - r-sp
  - r-spatialEco
  - r-tidyr
  - r-tidyverse
  - r-tmap
  - r-vcfR
  - r-vegan
  - r-wesanderson
  - pip:
    - ebird-api
    - geonomics
    - geopandas
    - intake_geopandas
    - nlmpy
    - PyPDF2
    - python-Levenshtein
    - rasterio
    - rio-hist
    - teapot
    - xeno-canto
